name: language_pack
description: Language support and word packs for the Gesture Charades app
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  core_models:
    path: ../core_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
